SEA-main/api/urls.py
from django.urls import path

from api import views

urlpatterns = [
    # Article 객체 관련 API
    path('article/<str:name>/<int:pk>', views.ArticleInfo.as_view(), name='article_info'),
]

SEA-main/bangdori/urls.py
from django.urls import path
from . import views

NAME = 'APP'
urlpatterns = [
    path('', views.goIndex, name='go'),
    path('index/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('idcheck/', views.id_check, name='idcheck'),
    path('detail/<int:pk>', views.DetailView.as_view(), name='detail'),
    # path('accountupdate/<int:pk>', views.AccountUpdateView.as_view(), name='update'),
    path('board/<str:name>/', views.board, name='board'),
    path('board/<str:name>/search/',
         views.SearchArticle.as_view(), name='searcharticle'),
    path('board/<str:name>/<int:pk>', views.article, name='article'),
    path('board/<str:name>/write/', views.write, name='write'),
    path('board/<str:name>/update/<int:pk>', views.update, name='update'),
    path('board/<str:name>/delete/<int:pk>', views.delete, name='delete'),
    path('board/<str:name>/<int:pk>/comment', views.comment, name='comment'),
    path('board/<str:name>/<int:pk>/comment/<int:commentId>',
         views.commentDelete, name='commentDelete'),
    path('board/upvote', views.upvote, name='upvote'),
    path('findID/', views.findID, name='findID'),
    path('findID/sms', views.SMS),
    path('sms/send', views.SmsSendView.as_view()),

    path('sms/auth', views.SmsVerifyView.as_view()),
    path('findPW1/', views.findPW1, name='findPW1'),
    path('findPW1/findPW2/', views.findPW2, name='findPW2'),
    path('login/kakao', views.kakaologin.as_view(), name='kakaoLogin'),
    path('login/kakao/callback/',
         views.kakaocallback.as_view(), name='kakaoCallback'),
    path('login/google', views.googlelogin.as_view(), name='googleLogin'),
    path('login/google/callback/',
         views.googlecallback.as_view(), name='googleCallback'),
    path('login/naver', views.naverlogin.as_view(), name='naverLogin'),
    path('login/naver/callback/',
         views.navercallback.as_view(), name='naverCallback'),
    path('findPW1/findPW2/smspw', views.SMSPW, name='smspw'),
    path('search/', views.SearchAll.as_view(), name='searchall'),

    path('findID/sms/ShowID', views.showID, name='showID'),
    path('findPW1/findPW2/smspw/showPW/', views.showPW, name='showPW')
]

SEA-main/profileapp/urls.py
from django.urls import path

from . import views
from .views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('view', views.view, name='view'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
    path('mypage/', views.mypage),
    path('myinfo/', views.myinfo, name='myinfo'),
    path('mypost/', views.mypost, name='mypost'),
    path('favorites/', views.favorites, name='favorites'),
    path('address/', views.Address.as_view(), name='address'),
    path('corporate/', views.corporate, name='corporate'),
    path('create/small/<int:pk>', views.AccountUpdateView.as_view(), name='small'),
]

SEA-main/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

# OpenAPI 관련 설정
schema_view = get_schema_view(
    openapi.Info(
        title="Bangdori",
        default_version="0.0.1",
        description="Bangdori API 문서",
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bangdori.urls'), name='bangdori'),
    path('profiles/', include('profileapp.urls')),

    path('api/', include('api.urls')),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

# MEDIA_ROOT 설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SEA-main/bangdori/models/Authentication.py
from django.db import models


class Authentication(models.Model):
    phone_number = models.CharField('휴대폰 번호', max_length=30)
    auth_number = models.CharField('인증번호', max_length=30)

    class Meta:
        db_table = 'authentications'  # DB 테이블명
        verbose_name_plural = "휴대폰인증 관리 페이지"  # Admin 페이지에서 나타나는 설명

SEA-main/bangdori/models/UpvoteHistory.py
from django.db import models


class UpvoteHistory(models.Model):
    """
    사용자가 게시물을 추천할 경우, 이에 대한 기록을 저장하는 Model

    Parameters
    ----------
    id : AutoField
        Integer 형식의 Auto Increment를 나타내는 PK
    user : ForeignKey
        추천한 사용자를 나타냄
    board : CharField
        게시판 이름 (예시 : succession)
    article_id : PositiveIntegerField
        게시판의 게시글 id를 나타내고, ForeignKey를 저장하기 위함
    upvote_at : DateTimeField
        추천한 시각을 나타냄
    """

    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(
        'CustomerUser', on_delete=models.CASCADE, verbose_name='user')
    board = models.CharField(max_length=50, verbose_name='board')
    article_id = models.PositiveIntegerField(
        db_column='article_id', null=False)
    upvote_at = models.DateTimeField(db_column='upvote_at', auto_now_add=True)

SEA-main/bangdori/views/Article.py
from django.shortcuts import render

from bangdori.utils import getModelByName, getCommentModelByName
from profileapp.models import Profile


def article(request, name, pk):
    """
    article : 게시글 내용을 보여주는 view
    """

    context = {}

    # 게시글 정보 불러옴
    article = getModelByName(name)
    need_addr = article().need_addr()
    article = article.objects.all().get(id=pk)
    comment = getCommentModelByName(name)

    try:
        comments = comment.objects.all().filter(article_id=article.id)
    except Exception as e:
        comments = None

    # 조회수 올림
    if request.user.id != article.writer_id or request.user.is_authenticated:
        # 본인 게시글이 아니면 조회수 올림
        article.views += 1

    article.save()

    writer_img = Profile.objects.all().filter(user=article.writer).last()
    if writer_img:
        writer_img = writer_img.image.url

    # Context에 전달
    context['article'] = article
    context['url'] = name
    context['comments'] = comments
    context['writer_img'] = writer_img
    if need_addr:
        context['need_addr'] = need_addr
        context['addr'] = article.addr
        context['lat'] = article.addr.lat
        context['lng'] = article.addr.lng

    return render(request, 'article.html', context)

SEA-main/bangdori/views/Board.py
from django.core.paginator import Paginator
from django.shortcuts import render

from bangdori.utils import getModelByName, getArticlesByAddress, getCommentModelByName
from project.settings import MAX_ARTICLES


def board(request, name):
    """
    board : 게시판 목록을 보여주는 view
    """

    # 페이지에 넘겨줄 Context
    context = {}

    # 게시판 내용 불러올 Article 객체
    articles = getModelByName(name)
    need_sorted_addr = articles().need_sorted_addr()

    # 페이지 정보 전달
    # context['name'] : 페이지가 표시되는 한글 이름
    context['name'] = articles._meta.verbose_name
    # context['url'] : 페이지에서 url로 전달받은 이름
    context['url'] = name

    # 모든 글 가져옴, 날짜 내림차순으로 조회
    articles = articles.objects.all().order_by('-date')

    # 주소 순으로 정렬이 필요한 경우
    if need_sorted_addr:
        articles = getArticlesByAddress(request.user, articles)

    # Paginator 사용
    paginator = Paginator(articles, MAX_ARTICLES)
    # GET 요청이 들어오면 page 파라미터를 읽어옴
    page = int(request.GET.get('page', 1))

    # 현재 페이지에 맞는 게시물 목록을 Context로 넘겨줌
    context['articles'] = paginator.get_page(page)

    # 댓글 가져옴
    comments = getCommentModelByName(name)
    context['comments'] = {x.id: comments.objects.all().filter(
        article_id=x).count() for x in context['articles']}
    return render(request, 'board.html', context)

SEA-main/bangdori/views/Comment.py
from django.shortcuts import redirect

from bangdori.utils import getModelByName, getCommentModelByName


def comment(request, name, pk):
    user = request.user
    Article = getModelByName(name)
    article = Article.objects.all().get(id=pk)
    comment = getCommentModelByName(name)

    if request.method == "POST":
        comment(article_id=article,
                content=request.POST.get('comment'),
                writer=user).save()

        return redirect('article', name=name, pk=pk)

SEA-main/bangdori/views/CommentDelete.py
from django.shortcuts import redirect, render


from bangdori.utils import getCommentModelByName, getModelByName


def commentDelete(request, name, pk, commentId):
    comment = getCommentModelByName(name)
    if request.method == "GET":
        comment.objects.all().get(id=commentId).delete()
        return redirect('article', name=name, pk=pk)

SEA-main/bangdori/views/Delete.py
from django.shortcuts import redirect, render

from bangdori.utils import getModelByName


def delete(request, name, pk):
    """
    update : 게시글 update하는 view
    """
    user = request.user
    Article = getModelByName(name)
    article = Article.objects.all().get(id=pk)

    if article.writer != user:
        return redirect('article', name=name, pk=pk)
    if request.method == "POST":
        # 게시글 수정
        article.delete()
        return redirect('board', name=name)

SEA-main/bangdori/views/DetailView.py
from django.views.generic import DetailView

from bangdori.models import CustomerUser


class DetailView(DetailView):
    model = CustomerUser
    context_object_name = 'target_user'
    template_name = 'myinfo.html'

SEA-main/bangdori/views/FindIDPW.py
from django.shortcuts import render


def findID(request):
    return render(request, 'findID.html')


def SMS(request):
    return render(request, 'temp_sms.html')


def SMSPW(request):
    return render(request, 'temp_smsPW.html')


def findPW1(request):
    return render(request, 'findPW1.html')


def findPW2(request):
    return render(request, 'findPW2.html')


def showID(request):
    return render(request, 'showID.html')

def showPW(request):
    return render(request, 'showPW.html')

SEA-main/bangdori/views/IDCheck.py
from django.http import JsonResponse

from bangdori.models import CustomerUser


def id_check(request):
    # 아이디나 닉네임이 존재하는지 확인, 둘 중 하나를 가져옴
    username = request.GET.get('user', None)
    nickname = request.GET.get('nickname', None)

    try:
        user = None

        # 경우에 따른 유효성 검사
        if username:
            user = CustomerUser.objects.all().filter(username=username).last()
        elif nickname:
            user = CustomerUser.objects.all().filter(nickname=nickname).last()
    except Exception as e:
        user = None
    result = {
        'result': 'success',
        'data': "not exist" if user is None else "exist"
    }

    return JsonResponse(result)

SEA-main/bangdori/views/Index.py
from django.shortcuts import redirect, render

from bangdori.models import BoardArticle, DabangArticle, SuccessionArticle, GroupArticle, EssentialsArticle
from bangdori.utils import getAllArticles, getCommentModelByName, addCommentsToTitle
from project.settings import INDEX_ARTICLES


def goIndex(request):
    return redirect('index')


def index(request):
    context = {}
    # 게시글 정보를 저장할 dict
    articles = {}
    # 게시글 데이터 가져옴
    data = getAllArticles()

    # 자를 갯수
    cut = INDEX_ARTICLES

    # 게시글이 없는 경우에 예외처리를 하지 않으면 오류가 날 수 있음
    if len(data) > 0:
        # 핫 게시물은 upvote 순으로 정렬
        # addCommentsToTitle로 댓글 수도 추가
        articles['best'] = addCommentsToTitle(sorted(data, key=lambda x: x['upvote'], reverse=True)[:cut])

        # 최신 게시물은 date 순으로 정렬
        articles['new'] = addCommentsToTitle(sorted(data, key=lambda x: x['date'], reverse=True)[:cut])

        # 각 게시판별 글
        articles['board'] = addCommentsToTitle(
            [x.to_dict() for x in BoardArticle.objects.all().order_by('-date')][:cut])
        articles['dabang'] = addCommentsToTitle(
            [x.to_dict() for x in DabangArticle.objects.all().order_by('-date')][:cut])
        articles['succession'] = addCommentsToTitle(
            [x.to_dict() for x in SuccessionArticle.objects.all().order_by('-date')][:cut])
        articles['group'] = addCommentsToTitle(
            [x.to_dict() for x in GroupArticle.objects.all().order_by('-date')][:cut])
        articles['essentials'] = addCommentsToTitle(
            [x.to_dict() for x in EssentialsArticle.objects.all().order_by('-date')][:cut])

        context['articles'] = articles
    return render(request, 'index.html', context)

SEA-main/bangdori/views/Logout.py
from django.contrib import auth
from django.shortcuts import redirect


def logout(request):
    # del 방식을 이용하지 않고, auth에서 제공하는 메서드를 이용
    auth.logout(request)
    return redirect('/index')

SEA-main/bangdori/views/Register.py
from django.contrib import auth
from django.shortcuts import render, redirect

from bangdori.models import CustomerUser


def register(request):
    if request.method == "GET":
        return render(request, 'register.html')
    elif request.method == "POST":
        # register로 POST 요청이 들어오면, 새로운 User를 생성하는 절차
        context = {}

        # 정보 저장
        username = request.POST.get('register_username', None)
        password = request.POST.get('register_user_pwd', None)
        password2 = request.POST.get('register_user_repwd', None)
        email_id = request.POST.get('register_user_email_id', None)
        # 이메일 도메인을 선택에 따라 분기
        email_net = request.POST.get('register_user_email', None)
        if email_net == 'direct':
            # 선택 상자의 const가 direct인 경우, 직접 입력된 칸을 받아옴
            email_net = request.POST.get('register_user_direct_email', None)

        year = request.POST.get('register_user_year', None)
        month = request.POST.get('register_user_month', None)
        day = request.POST.get('register_user_day', None)
        phone = request.POST.get('register_user_phone', None)
        nickname = request.POST.get('register_user_nickname', None)

        # 중복 확인
        if CustomerUser.objects.filter(username=username).exists():
            context['error'] = "사용할 수 없는 ID입니다."

        if password != password2:
            # 비밀번호 틀림
            context['error'] = "비밀번호가 다릅니다."
        elif not email_net:
            context['error'] = "이메일 주소를 입력해주세요."
        else:
            # DB에 저장
            user = CustomerUser.objects.create_user(username=username,
                                                    password=password2,
                                                    email=f'{email_id}@{email_net}',
                                                    birthday=f'{year}-{month}-{day}',
                                                    phone=phone,
                                                    nickname=nickname)

            # 로그인 후 메인으로 이동
            auth.login(request, user)
            return redirect('/')

        return render(request, 'register.html', context)

SEA-main/bangdori/views/Search.py
from django.shortcuts import render
from django.views import View

from bangdori.utils import getModelByName, getCommentModelByName


class SearchAll(View):
    """
    SearchAll : header에 위치하는 검색 기능을 사용하기 위한 클래스
    """

    def post(self, request):
        # 페이지에 넘겨줄 Context
        context = {}
        context['is_search'] = True
        context['is_global_search'] = True

        # 모든 게시판 객체 가져옴
        boards = getModelByName(None, True)
        # 검색어 가져옴
        keyword = request.POST.get('search_keyword')

        # 게시물 검색해오는 부분
        result = list()
        for board in boards:
            # 모든 게시판에서 키워드를 포함한 글을 가져옴
            articles = board.objects.all().filter(title__contains=keyword)
            # 검색 결과가 없는 것은 제외
            if articles.count() > 0:
                for article in articles:
                    # dict로 변환하여 저장
                    result.append(article.to_dict())

        # 날짜순으로 정렬
        result = sorted(result, key=lambda x: x['date'], reverse=True)
        context['articles'] = result
        context['keyword'] = keyword

        # 댓글 가져옴
        context['comments'] = {x['id']: getCommentModelByName(x['url']).objects.all().filter(
            article_id=x['id']).count() for x in context['articles']}


        # Pagination은 구현되어 있지 않음
        return render(request, 'board.html', context)


class SearchArticle(View):
    """
    SearchArticle : 게시판 내에서 검색을 위한 클래스
    """

    def post(self, request, name):
        # 페이지에 넘겨줄 Context
        context = {}
        context['is_search'] = True
        options = request.POST.get('search-type')

        # 모든 게시판 객체 가져옴
        board = getModelByName(name)
        # 검색어 가져옴
        keyword = request.POST.get('board-search-keyword')

        # 게시물 검색해오는 부분
        result = board.objects.all()

        # 조건에 맞도록 검색하는 부분
        if options == 'search-tc':
            x = result.filter(title__contains=keyword)
            x |= result.filter(content__contains=keyword)
            result = x
        elif options == 'search-t':
            result = result.filter(title__contains=keyword)
        elif options == 'search-c':
            result = result.filter(content__contains=keyword)
        elif options == 'search-w':
            result = result.filter(writer__username=keyword)
        elif options == 'search-cmt':
            pass

        # 날짜 순으로 정렬
        result = result.order_by('-date')

        context['articles'] = result
        # 게시판 내 검색이므로, 주소를 지정해주어야 함
        context['url'] = name

        # 댓글 가져옴
        comments = getCommentModelByName(name)
        context['comments'] = {x.id: comments.objects.all().filter(
            article_id=x).count() for x in context['articles']}

        # Pagination은 구현되어 있지 않음
        return render(request, 'board.html', context)

SEA-main/bangdori/templates/extends/banner.html
{% load static %}

<!-- 광고 배너 -->
<div class="ad-banner board-banner">
    <div class="banner-content">
        <div class="first banner showing">
            <img src={% static 'imgs/banner1.png' %} alt="배너" width="1024px" height="240px">
        </div>
        <div class="second banner">
            <img src={% static 'imgs/banner2.png' %} alt="배너" width="1024px" height="240px">
        </div>
        <div class="third banner">
            <img src={% static 'imgs/banner3.png' %} alt="배너" width="1024px" height="240px">
        </div>
        <div class="fourth banner">
            <img src={% static 'imgs/banner4.png' %} alt="배너" width="1024px" height="240px">
        </div>
        <div class="banner-count">
            <div class="first count js-clicked-count"></div>
            <div class="second count"></div>
            <div class="third count"></div>
            <div class="fourth count"></div>
        </div>
    </div>
</div>

SEA-main/bangdori/templates/extends/footer.html
{% load static %}

<!-- footer 정보 -->
<div class="footer">
    Copyright 2022. BangDori All rights reserved.
</div>

<!-- Scroll To top btn -->
<div class="scroll-top-btn">
    <span><a href="#header">TOP</a></span>
</div>

SEA-main/bangdori/templates/extends/header.html
{% load static %}

<!-- 로고 & 메뉴 -->
<div class="header">
    <div class="gnb">
        <div class="top-content">
            <!-- 로고 -->
            <div class="logo-box">
                <a href={% url 'index' %}>
                    <img class="logo" src="{% static 'imgs/logo.png' %}" alt="logo" width="288px"
                         height="76px"/></a>
            </div>

            <!-- 로고&웹사이트 설명 -->
            <div class="logo-title">
                <span>자취생들을 위한 커뮤니티</span>
            </div>

            <!-- 검색창 -->
            <div class="top-content-search">
                <form action="{% url 'searchall' %}" class="top-search-form" method="POST">
                    {% csrf_token %}
                    <div class="top-search-keyword-box">
                        <!-- 입력 창 -->
                        <input class="top-search-keyword" type="text" name="search_keyword" placeholder="검색" required/>
                        <img class="reset"
                             src="https://kr.seaicons.com/wp-content/uploads/2022/07/Very-Basic-Cancel-icon.png"
                             alt="cancel" onclick="resetKeyword()" width="15px"/>
                    </div>
                    <!-- 검색 버튼 -->
                    <input type="image" class="search"
                           src="https://www.pngall.com/wp-content/uploads/8/Vector-Search.png"
                           alt="search" width="25px"/>
                </form>
            </div>

            <!-- 미니로고 -->
            <div class="logo-on-search">
                <a href={% url 'index' %}><img class="logo" src="{% static 'imgs/logo_home.png' %}" alt="logo"
                                               width="86px" height="96px"></a>
            </div>
        </div>

        <!-- 메뉴 박스 -->
        <div class="menu-box">
            <div class="menu-list">
                <div class="menu-item">
                    <a href={% url 'board' name='dabang' %}>다방</a>
                </div>
                <div class="menu-item">
                    <a href={% url 'board' name='succession' %}>승계</a>
                </div>
                <div class="menu-item">
                    <a href={% url 'board' name='essentials' %}>자취생 필수템</a>
                </div>
                <div class="menu-item">
                    <a href={% url 'board' name='group' %}>공동 구매</a>
                </div>
                <div class="menu-item">
                    <a href={% url 'board' name='board' %}>자유 게시판</a>
                </div>
                <div class="menu-item">
                    <a href={% url 'board' name='notice' %}>공지사항</a>
                </div>
                <div class="menu-item">
                    <a href={% url 'board' name='contact' %}>문의하기</a>
                </div>
            </div>
        </div>
    </div>
</div>

SEA-main/bangdori/templates/extends/main.html
{% extends 'base_index.html' %}
{% load static %}
{% block main %}
    <!-- index 화면의 main 내용 -->
    <div class="main dabang_board">
        <div class="container">
            <div class="section">
                {% if 'index' in request.get_full_path %}
                    <!-- 자취생 필수템 및 로그인 박스 -->
                    <div class="article">
                        <!-- 자취생 필수템 미리보기 -->
                        <div class="preview-essentials">
                            <div class="preview-title" style="font-weight: 600; padding-top: 24px;">자취생 필수템</div>

                            <div class="preview-article essential-board essentials-board-size"
                                 style="border: 3px solid #96CEB4;">
                                {% if articles.essentials %}
                                    {% for article in articles.essentials %}
                                        {% if forloop.counter <= 3 %}
                                            <div class="box">
                                                <div class="card-title">
                                                    <a href="{% url 'article' name=article.url pk=article.id %}">
                                                        <img
                                                                {% if article.img %}
                                                                    src="{{ article.img.url }}"
                                                                {% else %}
                                                                    src="{% get_media_prefix %}defaults/no_image.jpg"
                                                                {% endif %}
                                                                    alt="" width="208px" height="128px">
                                                        {{ article.title }}
                                                    </a>
                                                </div>
                                                <div class="card-writer">
                                                    <span>{{ article.writer.nickname }}</span>
                                                </div>
                                                <div class="card-info">
                                                    <span class="js-date">{{ article.date }}</span>
                                                    <span>| 추천수: {{ article.upvote }}</span>
                                                </div>
                                            </div>
                                        {% endif %}
                                    {% endfor %}
                                {% endif %}
                                <div class="preview-more">
                                    <a class="more" href={% url 'board' name='essentials' %}>더보기 ...</a>
                                </div>
                            </div>
                        </div>

                        {% if request.user.is_authenticated %}
                            <!-- 로그인 이후 -->
                            <div id="after-login" class="article-box">
                                <!-- 로그인 이후 박스 -->
                                <div class="login-box after-login">
                                    <div class="login-after-user-info">
                                        <div style="border : 1px solid black; border-radius : 1rem; padding: 8px;">
                                            <div class="user-content-box">
                                                {% if request.user.profile.image.url %}
                                                    <img id="profile-img"
                                                         src="{{ request.user.profile.image.url }}"
                                                         alt="프로필 사진">
                                                {% else %}
                                                    <!-- 등록해놓은 이미지가 없으면 기본 이미지를 출력하도록 설정 -->
                                                    <img id="profile-img"
                                                         src="{% get_media_prefix %}profile/../../../media/defaults/default_profile.png"
                                                         alt="프로필 사진">
                                                {% endif %}
                                            </div>
                                            <div class="user-content-box">
                                                <snap id="nickname" class="user-content">{{ request.user.nickname }}님이
                                                    로그인 중
                                                </snap>
                                            </div>
                                            <hr>
                                            <div>
                                                <div class="user-content-box">
                                                    <div id="mileage" class="user-content">마일리지
                                                        : {{ request.user.mileage }}</div>
                                                    <div id="address" class="user-content">
                                                        {% if request.user.addr %}
                                                            <!-- 등록된 주소가 있는 경우, 주소를 출력 -->
                                                            {{ request.user.addr.city }} {{ request.user.addr.state }}
                                                        {% else %}
                                                            <!-- 등록된 주소가 없는 경우, 주소를 입력하는 사이트를 출력 -->
                                                            <a href="{% url 'profileapp:address' %}">[주소등록]</a>
                                                        {% endif %}
                                                    </div>
                                                </div>
                                                <hr>
                                                <div class="user-content-box">
                                                    <div id="mypage" class="user-content"
                                                         style="padding-left: 5px; padding-right: 12px;"><a
                                                            href="{% url 'profileapp:myinfo' %}"><input
                                                            type="button" id="mypage-button" value="My Page"></a></div>

                                                    <div id="logout" class="user-content"
                                                         style="padding-left: 5px; padding-right: 7px;"><a
                                                            href="{% url 'logout' %}"><input type="button"
                                                                                             id="logout-button"
                                                                                             value="로그아웃"></a></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <!-- 로그인 이전 박스 및 광고 -->
                            <div id="before-login" class="article-box">
                                <!-- 로그인 박스 -->
                                <div class="login-box">
                                    <div class="login-user">
                                        <a href={% url 'login' %}>
                                            <button id="login_btn">로그인</button>
                                        </a>
                                    </div>
                                    <div class="info-user">
                                        <a style="font-size : .9rem;" href={% url 'register' %}>회원가입</a>
                                        <div class="separate-line">|</div>
                                        <a style="font-size : .9rem;" href={% url 'findID' %}>아이디 찾기</a>
                                        <div class="separate-line">|</div>
                                        <a style="font-size : .9rem;" href={% url 'findPW1' %}>비밀번호 찾기</a>
                                    </div>
                                </div>
                                <!-- 광고 -->
                                <div class="small-ad">
                                    <img src="https://cdn.imweb.me/upload/S202012024cbcaa94f0469/3ef91e34b935f.png"
                                         alt="ad"
                                         width="226px" height="127px"/>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                {% endif %}

                <!-- content -->
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}