SEA-main/api/urls.py
from django.urls import path

from api import views

urlpatterns = [
    # Article 객체 관련 API
    path('article/<str:name>/<int:pk>', views.ArticleInfo.as_view(), name='article_info'),
]

SEA-main/profileapp/urls.py
from django.urls import path

from . import views
from .views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('view', views.view, name='view'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
    path('mypage/', views.mypage),
    path('myinfo/', views.myinfo, name='myinfo'),
    path('mypost/', views.mypost, name='mypost'),
    path('favorites/', views.favorites, name='favorites'),
    path('address/', views.Address.as_view(), name='address'),
    path('corporate/', views.corporate, name='corporate'),
    path('create/small/<int:pk>', views.AccountUpdateView.as_view(), name='small'),
]

SEA-main/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

# OpenAPI 관련 설정
schema_view = get_schema_view(
    openapi.Info(
        title="Bangdori",
        default_version="0.0.1",
        description="Bangdori API 문서",
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bangdori.urls'), name='bangdori'),
    path('profiles/', include('profileapp.urls')),

    path('api/', include('api.urls')),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

# MEDIA_ROOT 설정
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SEA-main/bangdori/models/Address.py
import math

from django.db import models


class Address(models.Model):
    """
    주소를 저장하는 Model

    Parameters
    ----------
    id : AutoField
        Integer 형식의 Auto Increment를 나타내는 PK
    postcode : IntegerField
        우편번호 (예시 : 13536)
    road : CharField
        도로명 주소 (예시 : 경기 성남시 분당구 판교역로 235)
    lot : CharField
        지번 주소 (예시 : 경기 성남시 분당구 삼평동 681)
    detail : CharField
        상세 주소
    extra : CharField
        도/시 이름 (예시 : 경기)
    state : CharField
        시/군/구 이름 (예시 : 성남시 분당구)
    road_name : CharField
        도로명 값, 검색 결과 중 선택한 도로명주소의 "도로명" 값
    lat : FloatField
        위도
    lng : FloatField
        경도
    """
    id = models.AutoField(primary_key=True)
    postcode = models.IntegerField(
        verbose_name='우편번호', null=True, default=None)
    road = models.CharField(
        max_length=50, verbose_name='도로명주소', null=True, default=None)
    lot = models.CharField(
        max_length=50, verbose_name='지번주소', null=True, default=None)
    detail = models.CharField(
        max_length=50, verbose_name='상세주소', null=True, default=None)
    extra = models.CharField(
        max_length=50, verbose_name='참고항목', null=True, default=None)
    city = models.CharField(
        max_length=10, verbose_name='도/시 이름', null=True, default=None)
    state = models.CharField(
        max_length=10, verbose_name='시/군/구 이름', null=True, default=None)
    road_name = models.CharField(
        max_length=10, verbose_name='도로명', null=True, default=None)
    lat = models.FloatField(verbose_name='위도', null=False)
    lng = models.FloatField(verbose_name='경도', null=False)

    def getTags(self):
        # 카카오에서 제공하는 data에 해당하는 Model 변수 이름 dict 반환
        return {'postcode': 'postcode', 'road': 'road', 'lot': 'jibun',
                'detail': 'detail', 'extra': 'extra', 'city': 'sido',
                'state': 'sigungu', 'road_name': 'roadname'}

    def __str__(self):
        return f'{self.road}{self.extra} {self.detail}'

    def createFromPost(self, request):
        # WSGIRequest를 통해 데이터를 받아와서 만들어줌
        try:
            self.postcode = int(request.POST.get('postcode'))
        except:
            pass

        self.road = request.POST.get('road')
        self.lot = request.POST.get('lot')
        self.detail = request.POST.get('detail')
        self.extra = request.POST.get('extra')
        self.city = request.POST.get('sido')
        self.state = request.POST.get('sigungu')
        self.road_name = request.POST.get('roadname')
        self.lat = float(request.POST.get('lat'))
        self.lng = float(request.POST.get('lng'))

        # 주소 모델 저장
        self.save()

        return self

    def calcDistance(self, another):
        # another 파라미터로 전달받은 다른 객체와의 거리를 계산
        # 경도 Lat, 위도 Lng과의 직선 거리 차이를 계산하여 출력함

        # 점과 점 사이의 거리이므로, 피타고라스 정리 이용
        return math.sqrt(math.pow(another.lat - self.lat, 2) + math.pow(another.lng - self.lng, 2))

SEA-main/profileapp/models.py
import uuid

from django.db import models
from django.conf import settings


# Create your models here.

def random_profile_img(instance, name):
    """ 무작위로 파일 이름 생성 """
    return "profile/%s.%s" % (uuid.uuid4(), name.split('.')[-1])

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile')
    image = models.ImageField(upload_to=random_profile_img, null=True)

SEA-main/profileapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ClearableFileInput, FileInput, ModelForm, TextInput
from .models import Profile


class ProfileCreateForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['image']
        widgets = {
            'image': FileInput(attrs={
                'class': 'pt_btn1',
            }),
        }


class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # self.fields['nickname'].disabled = True

SEA-main/bangdori/views/Update.py
from django.shortcuts import redirect, render

from bangdori.utils import getModelByName


def update(request, name, pk):
    """
    update : 게시글 update하는 view
    """
    user = request.user
    Article = getModelByName(name)
    article = Article.objects.all().get(id=pk)

    if article.writer != user:
        return redirect('article', name=name, pk=pk)

    if request.method == "POST":
        # 게시글 수정
        article.title = request.POST.get('title')
        article.content = request.POST.get('content')
        article.attr = request.POST.get('alignStatus')

        try:
            _, img = request.FILES.popitem()
            img = img[0]
            article.img = img
        except:
            pass

        article.save()
        return redirect('article', name=name, pk=pk)

    context = {}
    context['title'] = article.title
    context['content'] = article.content
    context['isEdit'] = True
    context['attr'] = article.attr

    try:
        context['img'] = article.img.url
    except:
        pass

    return render(request, 'write.html', context)

SEA-main/profileapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, UpdateView

import bangdori
from bangdori.models import CustomerUser, UpvoteHistory
from bangdori.utils import getModelByName
from .forms import ProfileCreateForm, AccountUpdateForm
from .models import *


# Create your views here.
class ProfileCreateView1(CreateView):
    model = Profile
    context_object_name = 'target_profile'
    form_class = ProfileCreateForm
    success_url = reverse_lazy('index')
    template_name = 'create.html'

    def form_valid(self, form):  # ProfileCreationForm의 data가 2번째 파라미터에 들어 있어요.
        # 임시로 저장함.<commit=False> 키워드 인자를 이용해서
        temp_profile = form.save(commit=False)
        temp_profile.user = self.request.user

        temp_profile.save()  # self는 view에서 가져온 self임. 또, 웹브라우저에서 입력 받은 값이 우항 좌항이 db에서 가져온값
        return super().form_valid(form)


class ProfileCreateView(View):
    def get(self, request):
        context = {}

        return render(request, 'create.html', context)

    def post(self, request):
        context = {}
        # 사진 업로드
        img = None
        try:
            _, img = request.FILES.popitem()
            img = img[0]
        except:
            pass

        if img:
            profile = Profile.objects.all().filter(user=request.user).last()
            if profile is None:
                profile = Profile(user=request.user)

            profile.image = img
            profile.save()

        request.user.nickname = request.POST.get('nicknameBox')
        request.user.save()

        return redirect('index')


class ProfileUpdateView(UpdateView):
    model = Profile
    context_object_name = 'target_profile'
    form_class = ProfileCreateForm
    success_url = reverse_lazy('index')
    template_name = 'update.html'

    def update(request, user_id):
        user = get_object_or_404(CustomerUser, pk=user_id)
        user.nickname = request.GET['nickname']
        user.save()
        return redirect('/index')


def view(request):
    return render(request, 'view.html')


def profile(request):
    return render(request, 'profile.html')


def mypage(request):
    return redirect('profileapp:myinfo')


def myinfo(request):
    """
    내 정보
    """
    context = {}
    user: CustomerUser = request.user
    context['email'] = user.email
    context['phone'] = user.phone

    if request.method == 'POST':
        user.set_password(request.POST.get('password'))
        user.email = request.POST.get('email')
        user.phone = request.POST.get('phone')

        user.save()

        return redirect('index')

    return render(request, 'myinfo.html', context)


def mypost(request):
    """
    내가 쓴 글
    """
    context = {}

    # 모든 게시판 객체 가져옴
    boards = getModelByName(None, True)

    # 게시물 검색해오는 부분
    result = list()
    for board in boards:
        # 모든 게시판에서 작성자가 현재 작성자인 글을 찾아옴
        articles = board.objects.all().filter(writer=request.user)
        # 검색 결과가 없는 것은 제외
        if articles.count() > 0:
            for article in articles:
                # dict로 변환하여 저장
                result.append(article.to_dict())

    # 날짜순으로 정렬
    result = sorted(result, key=lambda x: x['date'], reverse=True)
    context['articles'] = result

    return render(request, 'mypost.html', context)


def favorites(request):
    """
    즐겨찾기
    """
    context = {}

    # 내가 추천한 게시글 가져옴
    history = UpvoteHistory.objects.all().filter(user_id=request.user)

    # 모든 게시판 객체 가져옴
    boards = getModelByName(None, True)

    # 게시물 검색해오는 부분
    result = list()

    for h in history:
        # 추천한 게시판 객체 가져옴
        board = getModelByName(h.board)
        # 결과에 추가
        result.append(board.objects.all().filter(id=h.article_id).last().to_dict())

    # 날짜순으로 정렬
    result = sorted(result, key=lambda x: x['date'], reverse=True)
    context['articles'] = result
    return render(request, 'favorites.html', context)


def small(request):
    """
    닉네임 변경 작은 창
    """
    return render(request, 'small.html')


def corporate(request):
    """
    사업자 등록
    """
    context = {}

    corp = request.user.corp_num
    if not corp:
        corp = ""
    context['corp'] = corp

    if request.method == 'POST':
        request.user.corp_num = request.POST.get('corp')
        request.user.save()

        return redirect('profileapp:corporate')

    return render(request, 'corporate-registration.html', context)


class Address(View):
    def get(self, request):
        if request.user.is_anonymous:
            # 로그인되지 않은 상태
            return redirect(reverse('index'))

        context = {}
        context['addr'] = request.user.addr

        # 주소 등록 페이지
        return render(request, 'address.html', context)

    def post(self, request):
        # 주소 모델 생성
        addr = bangdori.models.Address().createFromPost(request)

        # 사용자 모델 가져옴
        user: CustomerUser = request.user
        # 이미 등록되어 있으면 해당 데이터를 삭제하고 저장
        if user.addr:
            user.addr.delete()

        # 저장
        user.addr = addr
        user.save()

        context = {}
        context['addr'] = request.user.addr

        # 주소 등록 페이지
        return render(request, 'address.html', context)


class AccountUpdateView(UpdateView):
    model = CustomerUser
    form_class = AccountUpdateForm
    context_object_name = 'target_user'
    success_url = reverse_lazy('index')
    template_name = 'small.html'

SEA-main/profileapp/templates/address.html
{% extends "extends/base.html" %}
{% load static %}
{% block mypage %}
    <div id="index-box">
        <div style="border-bottom :2px solid #96ceb4;"><br><br></div>
        <br>
        <div id="myinfo-list" class="index-list">내 정보</div>
        <div id="mynotice-list" class="index-list">내가 쓴 글</div>
        <div id="bookmark-list" class="index-list">추천 게시글</div>
        <div id="address-list" class="index-list clicked">주소 설정</div>
        <div id="corporate-list" class="index-list">사업자 등록</div>
    </div>

    <div id="content 여백" style="width : 10%"></div>

    <div>
        <h3>주소 설정</h3>
        <p>자신의 주소를 설정하고 변경할 수 있습니다.</p>
        {% include 'address_form.html' %}
    </div>

{% endblock %}

SEA-main/profileapp/templates/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>profile</title>
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>
<body>
<div>
    <div id="header">
        <div id='top' style="font-size:1.8rem">
            <a href="{% url 'index' %}">
                <img src="{% static 'imgs/logo.png' %}" alt="로고자리" style="height : 50px">
            </a>
        </div>
        <div id="lnb">
            <div class="lnb_contents">
                <div><h2 style="color: white;">방도리 간편 프로필 생성</h2></div>
                <div style="width : 600px"></div>
            </div>
        </div>
    </div>


    <div id="container">
        <div id="content">
            <div class="header">
                <h3>프로필 수정</h3>
                <p style="padding-top: color:#666">방도리 대표 프로필과 별명을 수정 하실 수 있습니다.</p>
            </div>
            <div>
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table class="tablestyle">
                        <tr class="tabletr">
                            <th class="tableth">프로필 사진</th>
                            <td style="padding : 0 50px; border-bottom : 1px solid #e5e5e5;">
                                <div>
                                    <div>
                                        {% if request.user.profile %}
                                            <img id="profile_pt" src="{{ request.user.profile.image.url }}"
                                                 alt="프로필 사진">
                                        {% else %}
                                            <img id="profile_pt" src="{% get_media_prefix %}defaults/default_profile.png"
                                                 alt="프로필 사진">
                                        {% endif %}
                                    </div>
                                    <input type="file" id="upload-image-file" name="upload-image-file"/>
                                </div>
                            </td>
                        </tr>

                        <tr class="tabletr">
                            <th class="tableth">별명 설정</th>
                            <td>
                                <div style="padding : 0 50px;">
                                    <input id="nicknameBox" class="nicknameBox" name="nicknameBox" type="text"
                                           value={{ request.user.nickname }}>
                                    <input id="nicknameBtn" class="check-btn button2" type="button" value="중복확인">
                                    <!--<a href="#"
                                   onclick="window.open('{% url 'profileapp:small' pk=request.user.id %}','name','x resizable=no width=300 height=200');return false">
                                    <button>변경</button>
                                </a>-->
                                </div>
                            </td>
                        </tr>
                    </table>
                    <div class="bottom">
                        <input class="button" type="submit" value="적용">
                        <input class="button" type="reset" value="취소">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'js/idcheck.js' %}"></script>
</body>
</html>

SEA-main/profileapp/templates/favorites.html
{% extends "extends/base.html" %}

{% block mypage %}
    <div id="index-box">
        <div style="border-bottom :2px solid #96ceb4;"><br><br></div>
        <br>
        <div id="myinfo-list" class="index-list">내 정보</div>
        <div id="mynotice-list" class="index-list">내가 쓴 글</div>
        <div id="bookmark-list" class="index-list clicked">추천 게시글</div>
        <div id="address-list" class="index-list">주소 설정</div>
        <div id="corporate-list" class="index-list">사업자 등록</div>
    </div>

    <div id="content 여백" style="width : 10%"></div>

    <div id="bookmark-box" class="content">
        <h3>추천 게시글 목록</h3>
        <p>자신이 추천한 게시물을 볼 수 있습니다.</p>
        <div>
            <div class="top-info">
                <div class="id">번호</div>
                <div class="title">제목</div>
                <div class="writer">글쓴이</div>
                <div class="date">작성일</div>
                <div class="views">조회</div>
                <div class="recommendation">추천</div>
            </div>
            <!-- 게시물 목록 -->
            <div class="writing-box">
                <!-- 게시물 목록 영역 -->
                {% if articles %}
                    {% for article in articles %}
                        <div class="article-info top-info">
                            <div class="id">{{ forloop.counter }}</div>
                            <div class="title">
                                <a href="{% url 'article' name=article.url pk=article.id %}">{{ article.title }}</a>
                            </div>
                            <div class="writer">{{ article.writer }}</div>
                            <div class="date js-date">{{ article.date }}</div>
                            <div class="views">{{ article.views }}</div>
                            <div class="recommendation">{{ article.upvote }}</div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <!-- 페이지 번호 영역 -->
            <div class="paging-box">
                            <span class="current">
                                        <a href="?page=1">1</a>
                                    </span>
            </div>
        </div>
    </div>
{% endblock %}

SEA-main/profileapp/templates/myinfo.html
{% extends "extends/base.html" %}
{% block mypage %}
    <div id="index-box">
        <div style="border-bottom :2px solid #96ceb4;"><br><br></div>
        <br>
        <div id="myinfo-list" class="index-list clicked">내 정보</div>
        <div id="mynotice-list" class="index-list">내가 쓴 글</div>
        <div id="bookmark-list" class="index-list">추천 게시글</div>
        <div id="address-list" class="index-list">주소 설정</div>
        <div id="corporate-list" class="index-list">사업자 등록</div>
    </div>

    <div id="content 여백" style="width : 10%"></div>

    <div id="content-box">
        <form method="post" action="">
            {% csrf_token %}
            <div id="myinfo-box" class="content">
                <h3>내 정보 설정</h3>
                <p>내 정보를 확인하고 설정할 수 있습니다.</p>
                <table>
                    <!--
                    <tr>
                        <th>닉네임</th>
                        <td>
                            <input type="text" value="{{ request.user.nickname }}">
                            <input type="button" value="변경" class="button">
                        </td>
                    </tr>

                    <tr>
                        <th>이름</th>
                        <td><input type="text" value="사용자 이름"></td>
                    </tr>
                    <tr>
                        <th>아이디</th>
                        <td>
                            <input type="text" value="사용자 아이디">
                            <input type="button" value="확인">
                        </td>
                    </tr> -->
                    <tr>
                        <th>비밀번호</th>
                        <td><input type="password" name="password" required></td>
                    </tr>
                    <tr>
                        <th>이메일</th>
                        <td><input type="text" name="email" value="{{ email }}" required></td>
                    </tr>
                    <tr>
                        <th>전화번호</th>
                        <td><input type="text" name="phone" value="{{ phone }}" required></td>
                    </tr>
                    {% if target_user.profile %}
                        <tr>
                            <th>프로필</th>
                            <td><a href="{% url 'profileapp:update' pk=target_user.profile.pk %}">프로필 수정</a></td>
                        </tr>
                    {% else %}
                        <tr>
                            <th>프로필</th>
                            <td><a href="{% url 'profileapp:create' %}">프로필 생성</a></td>
                        </tr>
                    {% endif %}
                </table>
                <div class="bottom">
                    <input class="button" type="submit" value="적용">
                    <input class="button" type="submit" value="취소">
                </div>
            </div>

        </form>
    </div>
{% endblock %}

SEA-main/profileapp/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>profile</title>
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>
<body>
<div>
    <div id="header">
        <div id='top' style="font-size:1.8rem">
            <a href="{% url 'index' %}">
                <img src="{% static 'imgs/logo.png' %}" alt="로고자리" style="height : 50px">
            </a>
        </div>
        <div id="lnb">
            <div class="lnb_contents">
                <div><h2>방도리 간편 프로필 변경</h2></div>
                <div style="width : 600px"></div>
                <div class="lnb_mypage"><a href="{% url 'myinfo' %}"><b>My Page →</b></a></div>

            </div>
        </div>
    </div>

    <div id="container">
        <div id="content">
            <div class="header">
                <h3>프로필 수정</h3>
                <p style="padding-top: color:#666">방도리 대표 프로필과 별명을 수정 하실 수 있습니다.</p>
            </div>
            <div>
                <table class="tablestyle">
                    <tr class="tabletr">
                        <th class="tableth">프로필 사진</th>
                        <td style="padding : 0 50px; border-bottom : 1px solid #e5e5e5;">
                            <div>
                                <div>
                                    {% if request.user.profile %}
                                        <img id="profile_pt" src="{{ request.user.profile.image.url }}" alt="프로필 사진">
                                    {% else %}
                                        <img id="profile_pt" src="{% get_media_prefix %}defaults/default_profile.png"
                                             alt="프로필 사진">
                                    {% endif %}
                                </div>

                                <div class="pt_button">
                                    <form action="{% url 'profileapp:create' %}" method="post"
                                          enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {{ form.image }}
                                        <!--                                        <input class = "pt_btn1" type="file" value="파일">-->
                                        <!--                                        <input class = "pt_btn" type="button" value="기본사진">-->
                                        <!--                                        <input class = "pt_btn" type="button" value="삭제">-->
                                </div>
                            </div>
                        </td>
                    </tr>

                    <tr class="tabletr">
                        <th class="tableth">별명 설정</th>
                        <td>
                            <div style="padding : 0 50px;">
                                <input id="input_nic" type="text" value={{ request.user.nickname }} name="nickname">
                                <!--                                    <input id ="nic_submit" type="submit" value="확인">-->
                                <input id="nicknameBtn" class="check-btn" type="button" value="중복확인">
                            </div>
                        </td>
                    </tr>
                </table>
            </div>

            <div class="bottom">
                <input class="button" type="submit" value="적용">
                <input class="button" type="submit" value="취소">
            </div>
            </form>
        </div>
    </div>
</div>
<script src="{% static 'js/idcheck.js' %}"></script>
</body>
</html>

SEA-main/profileapp/templates/small.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <meta charset="UTF-8">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <title>닉네임 변경 창</title>
</head>
<body>
<div style="display : flex; height : 200px;justify-content:space-between; align-items : center;">
    <!--        {{form}}-->
    <input id="nickname" type="text" value={{ request.user.nickname }}>
    <input id="nicknameBtn" class="check-btn button2" type="button" value="중복확인">
    <input type="submit" class="button2" value="적용">
    <!--        </form>-->
</div>
<script src="{% static 'js/idcheck.js' %}"></script>
</body>
</html>

SEA-main/profileapp/templates/update.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>profile</title>
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>

<body>
<div>
    <div id="header">
        <div id='top' style="font-size:1.8rem">
            <a href="{% url 'index' %}">
                <img src="{% static 'imgs/logo.png' %}" alt="로고자리" style="height : 50px">
            </a>
        </div>
        <div id="lnb">
            <div class="lnb_contents">
                <div><h2 style = "color: white;">방도리 간편 프로필 변경</h2></div>
                <div style="width : 600px"></div>
                <div class="lnb_mypage"><a href=""><b>My Page →</b></a></div>

            </div>
        </div>
    </div>

    <div id="container">
        <div id="content">
            <div class="header">
                <h3>프로필 수정</h3>
                <p style="padding-top: color:#666">방도리 대표 프로필과 별명을 수정 하실 수 있습니다.</p>
            </div>
            <div>
                <table class="tablestyle">
                    <tr class="tabletr">
                        <th class="tableth">프로필 사진</th>
                        <td style="padding : 0 50px; border-bottom : 1px solid #e5e5e5;">
                            <div>
                                <div>
                                    {% if request.user.profile %}
                                        <img id="profile_pt" src="{{ request.user.profile.image.url }}" alt="프로필 사진">
                                    {% else %}
                                        <img id="profile_pt" src="{% get_media_prefix %}defaults/default_profile.png"
                                             alt="프로필 사진">
                                    {% endif %}
                                </div>

                                <div class="pt_button">
                                    <form action="{% url 'profileapp:update' pk=target_profile.pk %}" method="post"
                                          enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {{ form.image }}
                                        <!--                                        <input class = "pt_btn1" type="file" value="파일">-->
                                        <!--                                        <input class = "pt_btn" type="button" value="기본사진">-->
                                        <!--                                        <input class = "pt_btn" type="button" value="삭제">-->
                                </div>
                            </div>
                        </td>
                    </tr>

                    <tr class="tabletr">
                        <th class="tableth">별명 설정</th>
                        <td>
                            <div style="padding : 0 50px;">
                                <input id="nicknameBox" type="text" value={{ request.user.nickname }}>
                                <!--                                    <input id ="nic_submit" type="submit" value="확인">-->
                                <input id="nicknameBtn" class="check-btn" type="button" value="중복확인">
                            </div>
                        </td>
                    </tr>
                </table>
            </div>

            <div class="bottom">
                <input class="button" type="submit" value="적용">
                <input class="button" type="submit" value="취소">
            </div>
            </form>
        </div>
    </div>
</div>
<script src="{% static 'js/idcheck.js' %}"></script>
</body>
</html>